<a href="https://colab.research.google.com/github/ayankhan434/DATA-SCIENCE/blob/main/pandas_class4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 4: Data Selection & Filtering
Welcome to **Class 4** of our Pandas series. Today we’ll explore techniques to select and filter data in a DataFrame.

## 1. Boolean Indexing & Conditional Selection
- Use comparison operators to build conditions (e.g., `df['col'] > 50`).
- Pass the condition inside `df[...]` to get matching rows.
- Combine multiple conditions with `&` (AND), `|` (OR), and `~` (NOT).
- Parentheses are required when combining conditions.

In [7]:
import numpy as np
import pandas as pd
a= {
    "Name":["Alice","Bob","Charlie","David","Emma"],
    "Age":[25,None,34,45,None],
    "City":["Delhi","Mumbai",None,"Banglore","chennai"],
    "Score":[34,23,32,np.nan,78]
}
b=pd.DataFrame(a)
b

      Name   Age      City  Score
0    Alice  25.0     Delhi   34.0
1      Bob   NaN    Mumbai   23.0
2  Charlie  34.0      None   32.0
3    David  45.0  Banglore    NaN
4     Emma   NaN   chennai   78.0

## 2. Filtering Rows with Multiple Conditions
- Combine two or more conditions to refine selection.
- Remember to enclose each condition in parentheses.

In [5]:
b.isna().sum()

Name     0
Age      2
City     1
Score    1
dtype: int64

## 3. Using `query()` for Cleaner Filtering
- `query()` allows filtering rows with a string expression.
- It's concise and readable for complex conditions.
- Variables can be passed using the `@` symbol.

In [12]:
b.dropna()

b['Age']=b['Age'].fillna(b['Age'].mean())
b['City']=b['City'].fillna(b['City'].mode())
b['Score']=b['Score'].fillna(b['Score'].mean())
b.isna().sum

b

      Name        Age      City  Score
0    Alice  25.000000     Delhi  34.00
1      Bob  34.666667    Mumbai  23.00
2  Charlie  34.000000    Mumbai  32.00
3    David  45.000000  Banglore  41.75
4     Emma  34.666667   chennai  78.00

## 4. String Operations on Columns
- Use the `.str` accessor for vectorized string methods.
- Common methods: `contains`, `replace`, `startswith`, `endswith`, `lower`, `upper`.
- Useful for cleaning or filtering text data.

In [18]:
b['Score']=b['Score'].astype(int)
b

      Name        Age      City  Score
0    Alice  25.000000     Delhi     34
1      Bob  34.666667    Mumbai     23
2  Charlie  34.000000    Mumbai     32
3    David  45.000000  Banglore     41
4     Emma  34.666667   chennai     78

In [19]:
b['Name']=b['Name'].replace("Bob","ayan")
b

      Name        Age      City  Score
0    Alice  25.000000     Delhi     34
1     ayan  34.666667    Mumbai     23
2  Charlie  34.000000    Mumbai     32
3    David  45.000000  Banglore     41
4     Emma  34.666667   chennai     78

In [42]:

b.drop([1,2],axis=0)
b

    Name        Age      City  Score
0  Alice  25.000000     Delhi     34
3  David  45.000000  Banglore     41
4   Emma  34.666667   chennai     78

In [45]:
#detecting and remooving duplicates
data={
    "Name":["Alice","Alice","Charlie","Alice","Alice"],
    "Age":[25,25,34,45,25],
    "City":["Delhi","Delhi","Delhi","Banglore","chennai"],

}

df = pd.DataFrame(data)
df

      Name  Age      City
0    Alice   25     Delhi
1    Alice   25     Delhi
2  Charlie   34     Delhi
3    Alice   45  Banglore
4    Alice   25   chennai

In [46]:
df.duplicated()

0    False
1     True
2    False
3    False
4    False
dtype: bool

In [47]:
df.drop_duplicates()

      Name  Age      City
0    Alice   25     Delhi
2  Charlie   34     Delhi
3    Alice   45  Banglore
4    Alice   25   chennai

## Mini Practice
1. Build a DataFrame with columns such as Name, Age, City, Score.
2. Use boolean indexing to select rows where Age > 25.
3. Filter rows where City is either 'Delhi' or 'Mumbai'.
4. Use query() to find rows with Score >= 85 and Age < 35.
5. Clean a text column using str.replace or str.lower.

In [ ]:


# 1. Build a DataFrame with columns: Name, Age, City, Score


# 2. Use boolean indexing to select rows where Age > 25
# Write your code here

# 3. Filter rows where City is either 'Delhi' or 'Mumbai'
# Write your code here

# 4. Use query() to find rows with Score >= 85 and Age < 35
# Write your code here

# 5. Clean a text column using str.replace or str.lower
# Example: convert City names to lowercase or replace "delhi" with "New Delhi"
# Write your code here

---
## Summary
- Learned to use boolean indexing and conditional selection.
- Filtered rows with multiple conditions.
- Used `query()` for clean filtering.
- Applied string operations with the `.str` accessor.